login/urls.py
from django.urls import path
from . import views
urlpatterns = [
    path('', views.homepage, name='homepage'),
    path('login/', views.loginView, name='login'),
    path('logout/', views.logoutView, name='logout'),
]

projectkelompok/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('searchbar.urls')),
    path('',include('signup.urls')),
    path('', include('login.urls')),
    path('', include('review.urls')),
]

review/urls.py
from django.urls import path, re_path
from . import views

app_name = 'review'
urlpatterns = [
    path('review/', views.review, name='review_urls'),
    path('review/make_review', views.form),
    re_path('delete/(?P<delete_id>.*)/', views.delete, name='delete'),
]

searchbar/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views

urlpatterns = [
    path('searchpage/', views.searchpage, name="searchpage"),
    path('spaces/', views.lihatspaces, name ="lihat_spaces"),
    path('rent/<int:id>',views.rent,name = "rent"),
    path('process/',views.pricing)
]

signup/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from login import views as login_views
app_name = "signup"
urlpatterns = [
    path('signup/',views.signup,name = "signup"),
    path('login/',login_views.loginView,name = "login")
]

login/models.py
from django.db import models

# Create your models here.

review/models.py
from django.db import models

# Create your models here.
class ReviewModels(models.Model) :
    name = models.CharField(max_length = 30)
    email = models.EmailField(max_length = 30)
    review = models.TextField()

    def __str__(self):
        return self.name

searchbar/models.py
from django.db import models

class Spacesmodels(models.Model):
   
    nama = models.CharField(
        max_length = 50,
        default= " ",

    )
    kota = models.CharField(
        max_length=30,
        default=" ",
    )
 
    tipe = models.CharField(
        max_length = 30,
        default= " ",
    )
 
    harga = models.IntegerField(
        default= 0,
    )

    jam = models.IntegerField(
        default = 1,
    )
    

signup/models.py
from django.db import models

#create your models here

searchbar/forms.py
from django import forms

class Spaces(forms.Form):
    nama = forms.CharField(
        label = "Space Name", 
        max_length = 50
    )

    isiankota=(
        ('Depok','Depok'),
        ('Jakarta','Jakarta'),
        ('Bandung','Bandung'),
        ('Bogor','Bogor'),
    )
    kota =forms.ChoiceField(
        label =  "City",
        choices = isiankota, 
    )

    isiantipe=(
        ('Event Space','Event Space'),
        ('Meeting Room','Meeting Room'),
        ('Creative Studio','Creative Studio'),
        ('Working Space','Working Space'),
    )

    tipe = forms.ChoiceField(
        label = "Space Type", 
        choices = isiantipe, 
    )

    harga = forms.IntegerField(
        label = "Rate", 
    )
    jam = forms.IntegerField(
        label= "Hours"
    )

signup/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

# Create your models here
class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username','email','password1','password2']

login/views.py
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout


def homepage(request):
    context = {
        'judul' : 'homepage.'
    }

    template = None
    
    if request.user.is_authenticated: 
        template = 'homepage_logout.html'
    else:
        template = 'homepage.html'

    return render(request, template, context)

def loginView(request):
    context = {
        'judul' : 'Please log in to your account first to book your space.',
    }

    user = None
    if request.method == "GET":     
        if request.user.is_authenticated:
            return redirect('/spaces/')

    
    if request.method == "POST": # pragma: no cover
        username_login = request.POST['username']
        password_login = request.POST['password']

        user = authenticate(request, username=username_login, password=password_login)
        
        if user is not None:
            login(request, user) 
            return redirect('/spaces/')
        else:
            return redirect('/login/')
            
    return render(request, 'login.html', context)



@login_required
def logoutView(request): # pragma: no cover
    context = {
        'judul' : "Do you want to Logout?"
    }

    if request.method == "POST":
        if request.POST["logout"] == "Submit":
            logout(request)
        
        return redirect('homepage')

    
    return render(request, 'logout.html', context)

review/views.py
from django.shortcuts import render
from .models import ReviewModels
from django.http import HttpResponseRedirect

# Create your views here.
def review(request):
    create_review={
        'listReview' : ReviewModels.objects.all(),
    }
    return render(request, 'review.html', create_review)

def form(request):
    if request.method == 'POST' :
        name = request.POST['name']
        email = request.POST['email']
        review = request.POST['review']

        ReviewModels.objects.create(
            name = name,
            email = email,
            review = review
        ) 
        return HttpResponseRedirect("/review/")

def delete(request, delete_id):
    ReviewModels.objects.filter(id = delete_id).delete()
    return HttpResponseRedirect("/review/")

searchbar/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import *
from django.http import HttpResponseRedirect
from .forms import Spaces
from .models import Spacesmodels

# Create your views here.


def searchpage(request):
	return render(request, 'search.html')

def lihatspaces(request):
    all= Spacesmodels.objects.all()

    arg= {
        "previous": all
    }
    return render(request, "spaces.html",arg)

def add(request):
    val1 = request.GET['harga']
    val2 = request.GET['jam']
    res = val1 * val2
    return render(request,"price.html",{"result" : res})
    
def rent(request,id):
    rentee = get_object_or_404(Spacesmodels, pk = id)
    form = Spaces()
    arg = {
        "rentee":rentee,
        "form":form
    }
    if request.method == "POST":
        hours = request.POST['jam']
        rate = rentee.harga
        return pricing(request,rate,hours)
    else:
        return render(request,'rent.html',arg)

def pricing(request,rate,hours):
    price = int(rate) * int(hours)
    arguement = {
        "harga" : price
    }
    return render(request,"pricing.html",arguement)

signup/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth import views as auth_views
from .forms import UserRegisterForm
# Create your views here.
def signup(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Account Successfully created for {username}.")
            return redirect("/login/")
    else:
        form = UserRegisterForm()
    return render(request,'signupindex.html',{'form' : form})


    

login/templates/homepage.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Sarala" rel="stylesheet" type="text/css">


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/homepage.css' %}">

    <link rel="icon" href="/static/img/spacenow.jpg">
    <title>SpaceNow</title>
</head>


<body id="homepage">

    <header>
        {% include 'navbar.html' %}
        <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">
    </header>
    <center>

        <img style="border-radius: 100px;" src="/static/img/spacenow.jpg" alt="SpaceNow">

        <h1 style="margin-top: 50px;">
            We make it easy for you to find the right <br> space for every ocassion.
        </h1>

        <a href='/login'><button class="btn btn-secondary" style="margin: 20px;"> Login </button></a>  <a href='/signup'><button class="btn btn-primary" style="margin: 20px;"> Signup </button> </a>

    </center>

    </div>
</body>


</html>

login/templates/homepage_logout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css?family=Sarala" rel="stylesheet" type="text/css">


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/homepage.css' %}">

    <link rel="icon" href="/static/img/spacenow.jpg">
    <title>SpaceNow</title>
</head>


<body id="homepage">

    <header>
        {% include 'navbar.html' %}
        <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">
    </header>
    <center>

        <img style="border-radius: 100px;" src="/static/img/spacenow.jpg" alt="SpaceNow">

        <h1 style="margin-top: 50px;">
            <b>Hallo {{user}} </b>
        </h1>

        <a href='/logout'><button class="btn btn-secondary" style="margin: 20px;"> Logout </button></a>
        
    </center>

    </div>
</body>


</html>

login/templates/login.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Login | SpaceNow</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">


</head>

<body>
    <header>
        {% include 'navbar.html' %}
        <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">
    </header>

    <center>
        <h1 style="color:#2a70f1 ; margin-top : 50px;"> {{judul}} </h1>
        <br>

        <form method="POST">
            <div class="kotak">

                {% csrf_token %} <br>
                <label for="username"> Username :</label> <br>
                <input type="text" name="username" id="username"> <br>
                <label for="password"> Password :</label> <br>
                <input type="password" name="password" id="password"> <br>

                <button class="btn btn-secondary" type="submit" onclick="myFunction()"> Login </button> <br><br>
                <!-- <script>
                    function myFunction() {
                        if (input != None) {
                            continue;
                        } else {
                            alert("I am an alert box!");
                        }

                    }
                </script> -->
            </div>

        </form>

        <p style="font-size: 24px;"> Haven’t got any account yet? </p> <br>
        <a href="/signup/" style="font-size: 24px;"> Click Here </a>




    </center>


</body>

</html>

login/templates/logout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Sarala" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Rakkas" rel="stylesheet" type="text/css">

    <link rel="stylesheet" href="{% static 'css/login.css' %}">
    <link rel="icon" href="/static/img/MFA.png">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <script src="../static/js/jquery.js"></script>
    <!-- <script src="../static/js/ajax.js"></script>  -->


    <title>Logout</title>
</head>

<body>
    <header>
        {% include 'navbar.html' %}
    </header>
    <center class="kotak" style="margin-top: 150px; padding-bottom: 20px;"> <br>
        <h1> {{judul}} </h1>
        <h3 style="margin-top: 20px;"> {{user}}</h3>

        {% comment %} <h3 style="margin-top: 20px;">{{user}}</h3> {% endcomment %}

        <form method="post">
            {% csrf_token %} <br>
            <input type="submit" name="logout" onclick="myFunction()">
        </form>

        <script>
            function myFunction() {
            alert("OK, you're logouting now");
            }
        </script>
    </center>

</body>

</html>

review/templates/review.html
{% load static %}
<!DOCTYPE html>

<html lang = "en">
    <head>
        <title> SpaceNow</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel ="stylesheet" href = "{% static 'css/review.css' %}">
        <link rel="icon" href="/static/img/SpaceNow.jpg">

        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    </head>


    <body>
        {% include 'navbar.html'%}
        <center><h1 style = "padding-top:5%; font-size:30px; font-family: Muli;">Give Us Your Honest Review !</h1></center>
        <div class = "row justify-content-center">
            <form id = "form_review" method = "POST" action="make_review">
                {% csrf_token %}
                <div class = "textBox" style="padding-left:3vw; padding-right:3vw; padding-top:3vw; padding-bottom:2.5vw;">
                    <div><input style ="width:100%" type="text" name="name" id="name" placeholder="Enter your name"></div><br>
                    <div><input style ="width:100%" type="text" name="email" id="email" placeholder="Enter your email"></div><br>
                    <div><textarea style ="width:100%" id="review" name="review" placeholder="Give your review"></textarea></div> 
                </div> 
                <center><input class = "submit" type = "submit" value="Submit" name ="submit"></center>
              </form>
        </div>


        {% for review in listReview%}
            <div class = "row justify-content-center">
                 <div class="col" style = "padding-left: 30%;">                    
                    <br><br><br><br>
                    <div class = "row">
                        <strong><p style="text-align: left; "> {{review.name}} </p></strong>&emsp;
                        <p style="text-align: left;">( {{review.email}} )</p>
                        <br>
                    </div>
                    <div class = "row">
                        &emsp;<p class = "textBox" style="text-align: left; font-size: larger; color:white;padding-left:5%; padding-right:5%; margin-right:30%; margin-left:5%;"> {{review.review}} </p>
                        <a href="{% url 'review:delete' review.id %}" id="delete" class="btn btn-light btn-xs" role="button" style="margin-left:5%;" >Delete</a>
                    </div>
                </div>
            </div>
        {% endfor %} 
<!-- 
        <div class="accordion">
                <center><h3 name = "Review" id = "accorTitle">Review</h3></center>
                  <div>
                  </div>
            </div>
        
         -->
        
        <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">

<!-- ini penutup -->
    </body>

    <script type = "text/javascript">
        $(document).on('submit', '#form_review', function(e){
            e.preventDefault();
            $.ajax({
                url : 'make_review',
                type : 'POST',
                data: {
                    name:$('#name').val(),
                    email:$('#email').val(),
                    review:$('#review').val(),
                    csrfmiddlewaretoken:$('input[name=csrfmiddlewaretoken]').val()
                },
                success: function(data){
                    alert("your review has been created");
                    console.log(data);
                    window.location.replace('/review/');
                }
            });
            
        });
    </script>
</html>

searchbar/templates/pricing.html
{% load static %}
<!DOCTYPE html>

<html lang = "en">
    <head>
        <title>Pricing | SpaceNow</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

        <!-- <link rel ="stylesheet" href = "{% static 'spaces.css' %}"> -->
        <!-- <link rel="icon" href="/static/img/spacenow.jpg"> -->

        <link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    <body>
        {% include 'navbar.html' %}
        <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">
        <div class="text-center my-5 container">
            <h3 class="text-center fonttitle" > This is the estimated price for your rent:  </h3>
            <br>
            <h3 class = "text center fontingform"> IDR {{harga}}  </h3>
            <br>
            <br>
            <h3 class="text-center fonttitle" > Not from Indonesia? Simply convert the currency below.   </h3>
            <script src="http://www.geoplugin.net/javascript.gp" type="text/javascript"></script>
            <script src="http://www.google.com/jsapi" type="text/javascript"></script>
            <script src="http://www.geoplugin.net/ajax_currency_converter.gp" type="text/javascript"></script>
            <br>
            <input type='text' id='gp_amount' size='4' /> 
            <select id="gp_from"></select> to <select id="gp_to"></select>
            <br>
            <br>
            <p><input type='button' onClick='gp_convertIt()' value = 'Convert' /></p>
            <div id="gp_converted"></div>
            <script>gp_currencySymbols()</script>


        </div>
    </body>
</html>

searchbar/templates/rent.html
{% load static %}
<!DOCTYPE html>

<html lang = "en">
    <head>
        <title>Pricing | SpaceNow</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel ="stylesheet" href = "{% static 'css/rent.css' %}">

        <link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    </head>
    
        <body>
            {% include 'navbar.html' %}

            <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">

            <div class= "container my-5" >
                <div class = "text-center">
                    <table>
                        <br>
                        <br>
                        <br>
                        <h3 class = fontingform> This is the rent fee for each hour of your bookings</h3>
                        <br>
                        <h3>IDR {{rentee.harga}} /hour</h3><br>
                        <form class= "rentajax" method = "POST">
                            {% csrf_token %}
                            <br>
                            <h3 class = fontingform> How long will you rent the space for?<br></h3>
                            <br>
                            <h3 id =renthours>{{form.jam}} hour(s). </h3> <br> 
                            <!-- <input type="submit" value="Submit">  -->
                            <button id="btncal" class = "btn btn-dark border-white"type="submit" >Calculate </button>
                            <br>

                        </form>
                        
                    </table>
              </div>    
            </div>

            <!-- <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

            <script>
                $(document).ready(function(){
                   var rentform = $('.rentajax')
                   rentform.submit(function(event){
                       event.preventDefault(); 
                       var thisform = $(this)
                    //    var action = thisform.attr("action"); 
                       var httpmethod =thisform.attr('method'); 
                       var formdata = thisform.serialize();

                       $.ajax({
                           url: 'rent/<int:id>',
                           method: httpmethod, 
                           data : formdata, 
                           success: function (data){

                           }, 
                           
                       })

                    })
                })

            </script> 
         jQuery first, then Popper.js, then Bootstrap JS 
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->
    </body>
</html>

searchbar/templates/search.html
{% load static %}
<!DOCTYPE html>

<html> 
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <link rel ="stylesheet" href = "{% static 'css/searchpage.css' %}">


    </head>
    <body>
        {% include 'navbar.html' %}

        <div class="col-12 toggle"></div>
        <link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">
    
        <div class="content">
            <h1 class = "font1 text-center">Look up our spaces <a id= btnhere href = '/spaces/'>here</a>!</h1><br><br>

            <p class = "font3 text-center">What type of and where you can find our spaces :</p>
            <div class="accordion" id="accordionExample">
                    <div class="card">
                      <div class="card-header" id="headingOne">
                        <h2 class="mb-0">
                          <button class="font1 btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                            Location
                          </button>
                        </h2>
                      </div>
                  
                      <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
                        <div class="card-body">
                            Depok<br>
                            Bogor <br>
                            Jakarta<br>
                            Bandung<br>
                        </div>
                      </div>
                    </div>
                    <div class="card">
                      <div class="card-header" id="headingTwo">
                        <h2 class="mb-0">
                          <button class="font1 btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                            Type
                          </button>
                        </h2>
                      </div>
                      <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
                        <div class="card-body">
                            Event Space<br>
                            Meeting Room <br>
                            Creative Studio <br>
                            Working Space <br>
                        </div>
                      </div>
                    </div>
                </div>
            </div>
            <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>

            <script type="text/javascript">
                $(document).ready(function(){
                    $('.toggle').click(function(){
                        $('.toggle').toggleClass('active')
                        $('body').toggleClass('night')
                        $('.card-header').toggleClass('night')
                        $('.card-body').toggleClass('night')
                    })
                })
            </script> 
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

templates/navbar.html
{% load static %}
<!--NAVBAR-->

<style>
    /*NAVBAR TOP */
    
    .button {
        font-family: Muli;
        font-style: normal;
        font-weight: bold;
        font-size: 1vw;
        text-align: center;
        color: #2F4B6E !important;
        padding: auto;
        width: auto;
        letter-spacing: 0.1em;
        -webkit-transition-duration: 0.4s;
        transition-duration: 0.4s;
    }
    
    .stay {
        color: #2F4B6E !important;
        letter-spacing: 0.1em;
        font-family: Muli;
        font-style: normal;
        font-weight: bold;
        font-size: 1vw;
        text-align: center;
        padding: auto;
        width: auto;
    }
    
    .button:hover {
        background-color: #C4C4C4;
        border-radius: 12px;
    }
    
    .fontingc2:hover {
        color: #C4C4C4;
    }
</style>

<link href="https://fonts.googleapis.com/css?family=Muli&display=swap" rel="stylesheet">

<header>
    <nav class="navbar navbar-expand-lg navbar-light bg-transparant" role=navigation>
        <div class=mr-auto>
            <ul class="nav navbar-nav ">
                <li class=" hover nav-item ">
                    <a class="stay nav-link active" href="/">SpaceNow</a>
                </li>
            </ul>
        </div>
        <div class=ml-auto>
            <ul class="nav navbar-nav ">
                <li class=" hover nav-item">
                    <a class="button nav-link" href="{% url 'login'%}">ACCOUNT</a>
                </li>
                <li class=" hover nav-item">
                    <a class="button nav-link" href="{% url 'searchpage'%}">SPACES</a>
                </li>
                <li class="hover nav-item active">
                    <a class="button nav-link" href="{% url 'lihat_spaces'%}">RENT</a>
                </li>
                <li class="hover nav-item">
                    <a class="button nav-link" href="{% url 'review:review_urls'%}">REVIEW</a>
                </li>
            </ul>
        </div>
    </nav>
</header>